apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
spec:
  rules:
  - host: demo.elwin.aws.cloud.nordstrom.net
    http:
      paths:
      - backend:
          serviceName: test1
          servicePort: 80
